name: build and test

on:
  push:
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
